/**
 * Enumeration of standardized categories.
 */
export enum EWebManifestCategory {
    BOOKS = "books",
    BUSINESS = "business",
    EDUCATION = "education",
    ENTERTAINMENT = "entertainment",
    FINANCE = "finance",
    FITNESS = "fitness",
    FOOD = "food",
    GAMES = "games",
    GOVERNMENT = "government",
    HEALTH = "health",
    KIDS = "kids",
    LIFESTYLE = "lifestyle",
    MAGAZINES = "magazines",
    MEDICAL = "medical",
    MUSIC = "music",
    NAVIGATION = "navigation",
    NEWS = "news",
    PERSONALIZATION = "personalization",
    PHOTO = "photo",
    POLITICS = "politics",
    PRODUCTIVITY = "productivity",
    SECURITY = "security",
    SHOPPING = "shopping",
    SOCIAL = "social",
    SPORTS = "sports",
    TRAVEL = "travel",
    UTILITIES = "utilities",
    WEATHER = "weather",
}